import { test, expect } from '@playwright/test'
import { loginAs } from './fixtures/auth'

/**
 * Admin user smoke tests.
 *
 * Requires:
 *   E2E_ADMIN_EMAIL    — email of an admin account
 *   E2E_ADMIN_PASSWORD — password for that account
 *
 * Optional:
 *   E2E_READY_LESSON_URL — absolute path like /courses/:cid/:lid/edit for a
 *                          lesson that already has mux_status = 'ready'.
 *                          If not set, the tracks-manager test is skipped.
 *
 * Selector notes for LessonForm:
 * - Labels are plain <label> text nodes (no htmlFor) wrapping the input.
 *   We use page.getByText() to find the label then .locator('..') to find
 *   sibling inputs — or simply locate inputs by proximity to the label text.
 *   The most robust approach for this component is to get the label element
 *   and then use .locator('input') / .locator('textarea') on its parent div.
 */

const adminEmail = process.env.E2E_ADMIN_EMAIL
const adminPassword = process.env.E2E_ADMIN_PASSWORD

test.describe('Admin flows', () => {
  test.skip(!adminEmail || !adminPassword, 'E2E_ADMIN_EMAIL / E2E_ADMIN_PASSWORD not set')

  test('admin creates a lesson and lands on edit page with upload widget', async ({ page }) => {
    await loginAs(page, adminEmail!, adminPassword!)
    await page.goto('/courses')

    const firstCourse = page.locator('a[href^="/courses/"]').first()
    if ((await firstCourse.count()) === 0) {
      test.skip(true, 'No published courses — create one first')
      return
    }
    const href = await firstCourse.getAttribute('href')

    await page.goto(`${href}/add-lesson`)

    // LessonForm labels are plain text inside <label> elements without htmlFor.
    // We locate the parent .field div then its child input/textarea.
    const titleField = page.locator('label', { hasText: 'Título' }).locator('..').locator('input')
    const descField = page.locator('label', { hasText: 'Descripción' }).locator('..').locator('textarea')
    const orderField = page.locator('label', { hasText: 'Orden' }).locator('..').locator('input[type="number"]')

    await titleField.fill(`E2E smoke test ${Date.now()}`)
    await descField.fill('Generated by Playwright smoke test')
    await orderField.fill('99')

    await page.getByRole('button', { name: /Crear lección/i }).click()

    // After successful creation the action redirects to /courses/:cid/:lid/edit
    await page.waitForURL(/\/edit$/, { timeout: 10_000 })
    await expect(page.getByRole('heading', { name: /Editar Lección/i })).toBeVisible()

    // VideoUploadWidget renders an h3 "Vídeo" regardless of upload status
    await expect(page.getByRole('heading', { name: /^Vídeo$/i })).toBeVisible()

    // MuxTracksManager should NOT be visible yet (mux_status is 'pending_upload')
    await expect(page.getByRole('heading', { name: /Pistas de audio/i })).not.toBeVisible()
  })

  test('admin edit page shows tracks manager only when mux_status = ready', async ({ page }) => {
    const readyLessonUrl = process.env.E2E_READY_LESSON_URL
    if (!readyLessonUrl) {
      test.skip(true, 'E2E_READY_LESSON_URL not set (expects /courses/:cid/:lid/edit with ready asset)')
      return
    }
    await loginAs(page, adminEmail!, adminPassword!)
    await page.goto(readyLessonUrl)

    // MuxTracksManager renders two collapsible sections with these titles
    await expect(page.getByRole('heading', { name: /Pistas de audio/i })).toBeVisible()
    await expect(page.getByRole('heading', { name: /Subtítulos/i })).toBeVisible()
  })
})
